# Markdown linting configuration for Multi-Modal Physiological Sensing Platform
# This config ensures consistent documentation formatting

# Disable rules that don't fit our documentation style
MD013: false  # Line length - we use long lines in code blocks
MD033: false  # Allow inline HTML for advanced formatting
MD041: false  # Allow documents without H1 header (for fragments)

# Configure specific rules
MD003:
  style: "atx"  # Use # headers instead of underlined headers

MD004:
  style: "dash"  # Use - for unordered lists

MD007:
  indent: 2  # 2-space indentation for nested lists

MD024:
  allow_different_nesting: true  # Allow duplicate headers at different nesting levels

MD029:
  style: "ordered"  # Use consistent numbering in ordered lists

MD046:
  style: "fenced"  # Use ``` code fences instead of indented blocks

# Allow these patterns specific to technical documentation
MD034: false  # Allow bare URLs in documentation
MD036: false  # Allow emphasis used as headers in certain contexts
